# Setup
title:               yun's blog
tagline:             'for NLP & NLU'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 "https://gityunjae.github.io"
baseurl:             ''
paginate:            5
permalink:           pretty


# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

category_list: [ papers, diary, study, DLfS, math, DLfS2, etc ]
